### ISSUE TITLE
Create a dataset CSV file for the HBN

### ISSUE THREAD

**Issue by michellewang** [mollyolzinski/Federated-Learning#7]
- Start from data showcase Jupyter notebook
- Loop over each row of the participants dataframe
  - Get path to the participant's Freesurfer 6.0.0 results (see https://fcp-indi.s3.amazonaws.com/index.html#data/Projects/HBN/derivatives/Freesurfer_version6.0.0/)
  - Call function created in #8 
  - Add columns to the participants dataframe
- Save dataframe to file

**Comment by mayalakshman** [comment]
Developed script to merge participant data (age, sex) with Freesurfer data for HBN dataset.
